[CmdletBinding()]
param(
    [Parameter()]
    [string]$Port = '',

    [Parameter()]
    [string]$WifiSsid = '',

    [Parameter()]
    [string]$WifiPassword = '',

    [Parameter()]
    [string]$GatewayHostname = 'bedjet-gateway',

    [Parameter()]
    [switch]$BuildOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$FirmwareRoot = Join-Path $RepoRoot 'firmware'
$SecretsHeaderPath = Join-Path $FirmwareRoot 'include\wifi_secrets.h'
$ExampleHeaderPath = Join-Path $FirmwareRoot 'include\wifi_secrets.example.h'

function Write-Step {
    param([Parameter(Mandatory)][string]$Message)
    Write-Host ''
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([Parameter(Mandatory)][string]$Message)
    Write-Host "[ok] $Message" -ForegroundColor Green
}

function Get-PlatformIoCommand {
    foreach ($name in @('pio', 'platformio')) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($command -and $command.Source) {
            return $command.Source
        }
    }

    throw 'PlatformIO CLI not found. Install PlatformIO Core so pio/platformio is available on PATH.'
}

function Escape-CString {
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)

    return $Value.Replace('\', '\\').Replace('"', '\"')
}

function Write-WifiSecretsHeader {
    param(
        [Parameter(Mandatory)][string]$Ssid,
        [Parameter(Mandatory)][string]$Password,
        [Parameter(Mandatory)][string]$Hostname
    )

    $content = @(
        '#pragma once'
        ''
        '// Auto-generated by scripts/windows/Flash-BedJetGateway.ps1'
        ("#define WIFI_SSID `"{0}`"" -f (Escape-CString -Value $Ssid))
        ("#define WIFI_PASSWORD `"{0}`"" -f (Escape-CString -Value $Password))
        ("#define MDNS_HOSTNAME `"{0}`"" -f (Escape-CString -Value $Hostname))
    ) -join "`r`n"

    Set-Content -Path $SecretsHeaderPath -Value $content
}

Write-Step 'Step 1: PlatformIO CLI'
$platformio = Get-PlatformIoCommand
Write-Ok "PlatformIO: $platformio"

if ($WifiSsid) {
    Write-Step 'Step 2: write local Wi-Fi preseed'
    Write-WifiSecretsHeader -Ssid $WifiSsid -Password $WifiPassword -Hostname $GatewayHostname
    Write-Ok "Wrote $SecretsHeaderPath"
} elseif (-not (Test-Path $SecretsHeaderPath)) {
    Write-Step 'Step 2: Wi-Fi preseed skipped'
    Write-Host "No Wi-Fi values provided. The gateway will use setup AP mode unless you create $SecretsHeaderPath from $ExampleHeaderPath." -ForegroundColor Yellow
} else {
    Write-Step 'Step 2: reuse existing local Wi-Fi preseed'
    Write-Ok "Using existing $SecretsHeaderPath"
}

Write-Step 'Step 3: build firmware'
$buildArgs = @('run', '-e', 'esp32-s3-devkitc-1')
Push-Location $FirmwareRoot
try {
    & $platformio @buildArgs
    if ($LASTEXITCODE -ne 0) {
        throw "PlatformIO build failed with exit code $LASTEXITCODE"
    }

    Write-Ok 'Firmware build completed'

    if (-not $BuildOnly) {
        Write-Step 'Step 4: upload firmware'
        $uploadArgs = @('run', '-e', 'esp32-s3-devkitc-1', '-t', 'upload')
        if ($Port) {
            $uploadArgs += @('--upload-port', $Port)
        }

        & $platformio @uploadArgs
        if ($LASTEXITCODE -ne 0) {
            throw "PlatformIO upload failed with exit code $LASTEXITCODE"
        }

        Write-Ok 'Firmware upload completed'
    }
}
finally {
    Pop-Location
}
