[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_ota_8MB.csv
build_flags =
  -D WIFI_SSID=\"\"
  -D WIFI_PASSWORD=\"\"
  -D MDNS_HOSTNAME=\"bedjet-gateway\"
  -D BEDJET_SIMULATED_BACKEND=0
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
